AMD201official2/Models/ErrorViewModel.cs
namespace AMD201official2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AMD201official2/Models/Url.cs
using System.ComponentModel.DataAnnotations;
namespace AMD201official2.Models
{
	public class Url
	{
		public int Id { get; set; }

        [Required(ErrorMessage = "Link can not be empty")]
        [Url(ErrorMessage = "Input must be a link")]
        public string OriginalLink { get; set; }

		public string ShortLink { get; set; }
		// We need only 3 type data in our project here
	}
}

AMD201official2/Controllers/HomeController.cs
using AMD201official2.Data;
using AMD201official2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AMD201official2.Controllers
{
    public class HomeController : Controller
    {
		
		private readonly ILogger<HomeController> _logger;


		public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

		public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AMD201official2/Controllers/UrlApiController.cs
using Microsoft.AspNetCore.Mvc;
using AMD201official2.Models;
using AMD201official2.Repository;
using System;
using System.Collections.Generic;
using System.Transactions;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace AMD201official2.Controllers
{
	[Route("api/[controller]")]
	[ApiController]
	public class UrlApiController : ControllerBase
	{

		private readonly IUrlRepository _urlRepository;
		public UrlApiController(IUrlRepository urlRepository)
		{
			_urlRepository = urlRepository;
		}

		// GET: api/<ValuesController>
		[HttpGet]
		public IActionResult Get()
		{
			var urls = _urlRepository.GetUrls();
			return new OkObjectResult(urls);
		}

		// GET api/<ValuesController>/5
		[HttpGet("{id}")]
		public IActionResult Get(int id)
		{
			var url = _urlRepository.GetUrlByID(id);
			return new OkObjectResult(url);
		}

		// POST api/<ValuesController>
		[HttpPost]
		public IActionResult Post([FromBody] Url url)
		{
			using (var scope = new TransactionScope())
			{
				_urlRepository.InsertUrl(url);
				scope.Complete();
				return CreatedAtAction(nameof(Get), new { id = url.Id }, url);
			}
		}

		// PUT api/<ValuesController>/5
		[HttpPut("{id}")]
		public void Put(int id, [FromBody] Url url)
		{
		}

		// DELETE api/<ValuesController>/5
		[HttpDelete("{id}")]
		public IActionResult Delete(int id)
		{
			_urlRepository.DeleteUrl(id);
			return new OkResult();
		}
	}
}

AMD201official2/Controllers/UrlController.cs
using AMD201official2.Models;
using AMD201official2.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using System.Runtime.CompilerServices;


namespace AMD201official2.Controllers
{

	public class UrlController : Controller
	{
		private readonly AppDbContext _context;
		public UrlController(AppDbContext context)
		{
			_context = context;
		}

        public async Task<IActionResult> Index()
        {
            return View(await _context.Urls.ToListAsync());
        }

        // Get: Url/Details
        public async Task<IActionResult> Details (int? id)
		{
			if (id == null)
			{
				return NotFound();
			}
			var url = await _context.Urls.FirstOrDefaultAsync(url => url.Id == id);
			if (url == null) { return NotFound(); }
			return View(url);
		}

		public IActionResult Create()
		{
			ViewData["ShortenedUrl"] = RandomString(8);
			return View();
		}

		//Post: Url/Create
		[HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,OriginalLink,ShortLink")] Url url)
		{
			if (ModelState.IsValid)
			{
				_context.Add(url);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View();
		}

        // Get: Url/Remove/5
        public async Task<IActionResult> Remove(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var url = await _context.Urls
                .FirstOrDefaultAsync(url => url.Id == id);
            if (url == null)
            {
                return NotFound();
            }

            return View(url);
        }


        // Post: Url/Remove/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveConfirmed(int id)
        {
            var url = await _context.Urls.FindAsync(id);
            if (url != null)
            {
                _context.Urls.Remove(url);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // Get: Url/IDI/'short-link'
        public async Task<IActionResult> IDI(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var url = await _context.Urls
                .FirstOrDefaultAsync(url => url.ShortLink == id);
            if (url == null)
            {
                return NotFound();
            }
            return Redirect(url.OriginalLink);
            //return View(url);
        }

		// Post: Url/IDI/'short-link' Remain Unused
		//[HttpPost, ActionName("IDI")]
  //      [ValidateAntiForgeryToken]
  //      public async Task<IActionResult> IDIConfirmed(string id)
  //      {
  //          var url = await _context.Urls
  //              .FirstOrDefaultAsync(url => url.ShortLink == id);
  //          if (url == null)
  //          {
  //              return NotFound();
  //          }
  //          return Redirect(url.OriginalLink);
  //      }

  //      private bool UrlExists(int id)
  //      {
  //          return _context.Urls.Any(url => url.Id == id);
  //      }


		private static Random random = new Random();
		public static string RandomString(int length)
		{
			const string chars = "qwertyuiopasdfghjklzxcvbnmABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
			return new string(Enumerable.Repeat(chars, length)
				.Select(s => s[random.Next(s.Length)]).ToArray());
		}

        //Get: Url/Expand
        [HttpGet, ActionName("Expand")]
        public async Task<IActionResult> Expand(string ShortLink)
        {
            if (string.IsNullOrEmpty(ShortLink))
            {
                // Display message box using a tempdata message
                TempData["Message"] = "Link cannot be empty.";
                return View(); 
            }

            var url = await _context.Urls.FirstOrDefaultAsync(Url => Url.ShortLink == ShortLink);

            if (url == null)
            {
                ViewData["ErrorMessage"] = "Wrong URL, type again.";
                return View(); // Return the view with the error message
            }

            // Return the view with the URL model if found
            return View(url);
        }


    }
}

AMD201official2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Welcome";
}

<section class=" ="landing py-5>
    <div class="container">
        <div class="row align-items-center">

            <div class="col-lg-4">
                <img scr="" class="img-fluid" alt=""/>
            </div>

            <div class="col-12">
                <h1 class="display-4">SHORTLY </h1>
                <p class=" lead">
                    Get your shorten link now with easy operate.
                </p>
            </div>
        </div>
    </div>
</section>

<section class="features" id=" features">
    <div class="container">
        <div class="url-shorten-feature">
            <!-- Update action-->
            <form class="url-shorten-feature" id="url-shorten-feature"
            asp-controller="Url" 
            asp-action="Index">
                <div>
                    <h2></h2>
                    <p >
                        Shorten your link here  ↓
                    </p>
                </div class="button-box">
                <button type="submit" class="button-box" style=""> Get your link ! </button>
            </form>
            <div class="url-shorten-results"></div>
        </div>
    </div>

</section>

AMD201official2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/test.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AMD201official2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AMD201official2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" 
                            asp-controller="Home" 
                            asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="Url"
                               asp-action="Index">Your links</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="Url"
                               asp-action="Expand">Expand link</a>
                        </li>

                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AMD201official2 - <a asp-area="" asp-controller="Home" asp-action="Expand">Expand</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AMD201official2/Views/Url/Create.cshtml
@model Url
@{
    ViewData["Title"] = "Shorten URL";
    var shorturl = ViewData["ShortenedUrl"];
}

<h1>Create</h1>

<h4>UrlShorten</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="OriginalLink" class="control-label">Your Link</label>
                <input asp-for="OriginalLink" class="form-control" />
                <span asp-validation-for="OriginalLink" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input asp-for="ShortLink" class="form-control" value="@shorturl" type="hidden"/>
            </div>


            <div class="form-group mt-3">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

AMD201official2/Views/Url/Expand.cshtml
@model Url
@{
    ViewData["Title"] = "Expand URL";
    var shorturl = ViewData["ShortenedUrl"];
    var message = TempData["Message"] as string;
}

<h2>Expand URL</h2>

<form method="get">
    <div class="form-group">
        <label for="ShortLink">Enter Shortened URL:</label>

        <br /><br />

        <input type="text" class="form-control" id="ShortLink" name="ShortLink" />


        @if (!string.IsNullOrEmpty(message))
        {
            <div class="alert alert-danger" role="alert">
                @message
            </div>
        }
    </div>

    <br />

    <div class="form-group">
        <input asp-for="ShortLink" class="form-control" value="@shorturl" type="hidden" />
    </div>

    <button type="submit" class="btn btn-primary">Expand</button>
</form>

@if (Model != null)
{
    <div class="mt-3">
        <h3>Original URL:</h3>
        <p>@Model.OriginalLink</p>
    </div>
}

@section Scripts {
    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function () {
            var errorMessage = '@ViewData["ErrorMessage"]';
            if (errorMessage) {
                alert(errorMessage);
            }
        });
    </script>
}

AMD201official2/Views/Url/IDI.cshtml
@model Url
@{
	ViewData["Title"] = "Redirect";
}

<div class="container">
    <form asp-action="IDI">
        <input type="hidden" asp-for="ShortLink" />
        <input type="submit" value="Redirect" class="btn btn-danger" /> |
    </form>
</div>

AMD201official2/Views/Url/Index.cshtml
@model IEnumerable<Url>
@{
    ViewData["Title"] = "All short links";
}

<div class="container mt-4">
    <a class="btn btn-create" asp-action="Create">Add new</a>
</div>
<div class="container mt-4">
    @if (Model.Count() == 1)
    {
        <p>There is @Model.Count() shortened link in total</p>
    }
    else
    {
        <p>There are @Model.Count() shortened links in total</p>
    }
</div>

<div class="container custom-header-container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th class="custom-header" scope="col">@Html.DisplayNameFor(model => model.Id)</th>
                <th class="custom-header" scope="col">@Html.DisplayNameFor(model => model.OriginalLink)</th>
                <th class="custom-header" scope="col">@Html.DisplayNameFor(model => model.ShortLink)</th>
                <th class="custom-header" scope="col">Copy Short Link</th>
                <th class="custom-header" scope="col">Delete Link</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var url in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => url.Id)</td>
                    <td>@Html.DisplayFor(modelItem => url.OriginalLink)</td>
                    <td>
                        <a href="@url.OriginalLink" class="btn btn-primary">
                            @Html.DisplayFor(modelItem => url.ShortLink)
                        </a>
                    </td>
                    <td>
                        <button onclick="copyLink('@url.ShortLink')" class="btn btn-primary">
                            Copy
                        </button>
                    </td>
                    <td>
                        <a class="btn btn-outline-danger" asp-controller="Url" asp-action="Remove" asp-route-id="@url.Id">
                            Remove
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script type="text/javascript">
    function copyLink(shortLink) {
        const link = `https://localhost:7260/Url/IDI/${shortLink}`;
        navigator.clipboard.writeText(link).then(() => {
            alert(`Copied the link: ${link}`);
        }).catch(err => {
            console.error('Failed to copy: ', err);
        });
    }
</script>

AMD201official2/Views/Url/Remove.cshtml
@model Url
@{
	ViewData["Title"] = "Remove Url";
}

<h1>Remove</h1>

<h3>Are you sure you want to remove this link?</h3>
<h3>This action is irreversible!</h3>
<div class="info-box">
    <h4>Url</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OriginalLink)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OriginalLink)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ShortLink)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ShortLink)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Remove" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>